#!/usr/bin/env python3
import argparse
import json
import re
from pathlib import Path
from typing import Any, Dict, List, Tuple


def _normalize_text(s: str) -> str:
    s = (s or "").lower()
    return re.sub(r"[^0-9a-z\u4e00-\u9fff]+", "", s)


def _parse_srt_ts(ts: str) -> float:
    # 00:00:12,345 -> seconds
    hms, ms = ts.split(",")
    h, m, s = hms.split(":")
    return int(h) * 3600 + int(m) * 60 + int(s) + int(ms) / 1000.0


def _read_srt(path: Path) -> List[Dict[str, Any]]:
    raw = path.read_text(encoding="utf-8-sig")
    blocks = re.split(r"\r?\n\r?\n+", raw.strip())
    out: List[Dict[str, Any]] = []
    for b in blocks:
        lines = [x.strip() for x in b.splitlines() if x.strip()]
        if len(lines) < 2:
            continue
        ts_line = lines[1] if re.search(r"-->", lines[1]) else lines[0]
        m = re.search(r"(\d{2}:\d{2}:\d{2},\d{3})\s*-->\s*(\d{2}:\d{2}:\d{2},\d{3})", ts_line)
        if not m:
            continue
        st = _parse_srt_ts(m.group(1))
        ed = _parse_srt_ts(m.group(2))
        text_lines = lines[2:] if ts_line == lines[1] else lines[1:]
        text = " ".join(text_lines).strip()
        out.append({"start": st, "end": ed, "text": text})
    return out


def _read_aeneas_json(path: Path) -> List[Dict[str, Any]]:
    data = json.loads(path.read_text(encoding="utf-8-sig"))
    segs = ((data.get("alignment_result") or {}).get("segments") or [])
    out: List[Dict[str, Any]] = []
    for s in segs:
        st_us = int(s.get("start", 0) or 0)
        du_us = int(s.get("duration", 0) or 0)
        ed_us = int(s.get("end", st_us + du_us) or (st_us + du_us))
        out.append(
            {
                "start": st_us / 1_000_000.0,
                "end": ed_us / 1_000_000.0,
                "text": str(s.get("text", "")),
            }
        )
    return out


def _match_by_text(ref: List[Dict[str, Any]], pred: List[Dict[str, Any]]) -> List[Tuple[int, int]]:
    pairs: List[Tuple[int, int]] = []
    j = 0
    for i, r in enumerate(ref):
        rt = _normalize_text(r["text"])
        if not rt:
            continue
        best = -1
        for k in range(j, len(pred)):
            pt = _normalize_text(pred[k]["text"])
            if not pt:
                continue
            if rt in pt or pt in rt:
                best = k
                break
        if best < 0:
            # fallback nearest-by-index
            best = min(max(j, 0), len(pred) - 1) if pred else -1
        if best >= 0:
            pairs.append((i, best))
            j = min(best + 1, len(pred))
    return pairs


def _pct(vals: List[float], p: float) -> float:
    if not vals:
        return 0.0
    v = sorted(vals)
    idx = int(round((len(v) - 1) * p))
    return float(v[max(0, min(len(v) - 1, idx))])


def main() -> int:
    parser = argparse.ArgumentParser(description="Evaluate Aeneas alignment quality against reference SRT.")
    parser.add_argument("--aligned-json", required=True, help="Aligned json generated by align.py.")
    parser.add_argument("--ref-srt", required=True, help="Reference SRT (e.g. ASR transcript).")
    parser.add_argument("--output-json", default="", help="Optional evaluation output json path.")
    args = parser.parse_args()

    pred = _read_aeneas_json(Path(args.aligned_json))
    ref = _read_srt(Path(args.ref_srt))
    if not pred:
        raise ValueError("No segments found in aligned json.")
    if not ref:
        raise ValueError("No subtitle rows found in reference srt.")

    pairs = _match_by_text(ref, pred)
    rows = []
    start_abs_err = []
    end_abs_err = []
    dur_abs_err = []
    for i, j in pairs:
        r = ref[i]
        p = pred[j]
        ds = p["start"] - r["start"]
        de = p["end"] - r["end"]
        dd = (p["end"] - p["start"]) - (r["end"] - r["start"])
        row = {
            "ref_index": i,
            "pred_index": j,
            "ref_text": r["text"],
            "pred_text": p["text"],
            "ref_start": r["start"],
            "pred_start": p["start"],
            "start_delta_sec": ds,
            "end_delta_sec": de,
            "duration_delta_sec": dd,
        }
        rows.append(row)
        start_abs_err.append(abs(ds))
        end_abs_err.append(abs(de))
        dur_abs_err.append(abs(dd))

    summary = {
        "status": "success",
        "matched_pairs": len(rows),
        "ref_count": len(ref),
        "pred_count": len(pred),
        "start_abs_error_sec": {
            "p50": _pct(start_abs_err, 0.5),
            "p90": _pct(start_abs_err, 0.9),
            "max": max(start_abs_err) if start_abs_err else 0.0,
            "mean": (sum(start_abs_err) / len(start_abs_err)) if start_abs_err else 0.0,
        },
        "end_abs_error_sec": {
            "p50": _pct(end_abs_err, 0.5),
            "p90": _pct(end_abs_err, 0.9),
            "max": max(end_abs_err) if end_abs_err else 0.0,
            "mean": (sum(end_abs_err) / len(end_abs_err)) if end_abs_err else 0.0,
        },
        "duration_abs_error_sec": {
            "p50": _pct(dur_abs_err, 0.5),
            "p90": _pct(dur_abs_err, 0.9),
            "max": max(dur_abs_err) if dur_abs_err else 0.0,
            "mean": (sum(dur_abs_err) / len(dur_abs_err)) if dur_abs_err else 0.0,
        },
        "samples": rows[:20],
    }

    out_path = Path(args.output_json) if args.output_json else Path(args.aligned_json).resolve().parents[1] / "output" / "alignment_eval.json"
    out_path.parent.mkdir(parents=True, exist_ok=True)
    out_path.write_text(json.dumps(summary, ensure_ascii=False, indent=2), encoding="utf-8")

    print(str(out_path.resolve()))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())

